models/Products.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\SluggableBehavior;
use app\behaviors\ImageBehavior;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property int $name
 * @property int $category_id
 * @property string $price
 * @property string $description
 * @property int $preview_image_name
 * @property string $created_at
 * @property string $updated_at
 * @property int $is_active
 * @property string $slug
 * @property int $amount
 *
 * @property FavoriteProducts[] $favoriteProducts
 * @property Categories $category
 */
class Products extends \yii\db\ActiveRecord {

    public $preview_image_path;
    public $preview_image;

    public static function tableName() {
        return 'products';
    }

    public function behaviors() {
        return [
            'timestamps' => [
                'class' => TimestampBehavior::className(),
                'value' => new \yii\db\Expression('NOW()'),
            ],
            'slug' => [
                'class' => SluggableBehavior::className(),
                'attribute' => 'name',
            ],
            'preview_image' => [
                'class' => ImageBehavior::className(),
                'attribute' => 'preview_image',
                'source' => 'preview_image_name',
                'decorator' => 'preview_image_path',
            ],
        ];
    }

    public function rules() {
        return [
            [['name', 'category_id', 'price', 'description', 'is_active', 'amount'], 'required'],
            [['category_id', 'is_active', 'amount'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['preview_image_name'], 'string', 'max' => 64],
            [['price'], 'number'],
            [['description'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['slug'], 'string', 'max' => 255],
            [['name'], 'unique'],
            [['slug'], 'unique'],
            [['preview_image'], 'file'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Categories::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Назва',
            'category_id' => 'Категорія',
            'price' => 'Ціна',
            'description' => 'Інформація',
            'preview_image_name' => 'Preview Image Name',
            'created_at' => 'Дата/час створення',
            'updated_at' => 'Дата/час редагування',
            'is_active' => 'Активно',
            'slug' => 'Slug',
            'amount' => 'Кількість',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFavoriteProducts() {
        return $this->hasMany(FavoriteProducts::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory() {
        return $this->hasOne(Categories::className(), ['id' => 'category_id']);
    }

}

controllers/ProductsController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\controllers;

use Yii;
use app\models\search\ProductsOuterSearch;

/**
 * Description of ProductControllers
 *
 * @author mezinn
 */
class ProductsController extends \yii\web\Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['favorites'],
                'rules' => [
                    [
                        'actions' => ['favorites'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        $searchModel = new ProductsOuterSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionToggleFavorite($id) {
        Yii::error('controller');
        return Yii::$app->productsHelper->toggleFavorite($id);
    }

    public function actionFavorites() {
        return $this->render('favorites', ['dataProvider' => Yii::$app->user->identity->getFavoritesDataProvider()]);
    }

}

views/products/_favorite-template.php
<?php

use yii\helpers\StringHelper;
?>

<div class="thumbnail">
    <img src="<?= "/{$model->product->preview_image_path}" ?>" alt="...">
    <div class="caption">
        <h5 title="<?= $model->product->name ?>"><?= StringHelper::truncate($model->product->name, 30) ?></h5>
        <p><?= intval($model->product->price) ?></p>
        <p><a class="btn btn-danger" onclick="toggle_favorite(event)" data-id ="<?= $model->product->id ?>">Видалити</a></p>
    </div>
</div>

views/products/_template.php
<?php

use yii\helpers\StringHelper;
?>

<div class="thumbnail">
    <img src="<?= "/$model->preview_image_path" ?>" alt="...">
    <div class="caption">
        <h5 title="<?= $model->name ?>"><?= StringHelper::truncate($model->name, 30) ?></h5>
        <p><?= intval($model->price) ?></p>
        <?php if (Yii::$app->productsHelper->isFavorite($model->id)): ?>
            <p><a class="btn btn-danger" onclick="toggle_favorite(event)" data-id ="<?= $model->id ?>">Видалити</a></p>
        <?php else: ?>
            <p><a class="btn btn-default" onclick="toggle_favorite(event)" data-id ="<?= $model->id ?>">Зберегти</a></p>
        <?php endif; ?>
    </div>
</div>

views/products/favorites.php
<?php

use yii\widgets\ListView;
?>


<?php yii\widgets\Pjax::begin(['id' => 'favorites']); ?>
<div class="row">
    <?=
    ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_favorite-template',
        'options' => ['class' => 'products-list'],
        'itemOptions' => ['class' => 'product__thumb'],
    ])
    ?>

</div>
<?php yii\widgets\Pjax::end(); ?>
<script>
    function toggle_favorite(event) {
        event.preventDefault();
        $.ajax({
            url: '/products/toggle-favorite',
            data: {id: event.target.dataset.id},
            success: function (data, textStatus, jqXHR) {
                $.pjax.reload({container: "#favorites"});

            }
        });

    }
</script>

views/products/index.php
<?php

use yii\widgets\ListView;
?>


<?php yii\widgets\Pjax::begin(['id' => 'products']) ?>
<div class="row">
    <?=
    $this->render('/manage/products/_search', [
        'model' => $searchModel,
        'content' => ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_template',
            'options' => ['class' => 'products-list'],
            'itemOptions' => ['class' => 'product__thumb'],
])])
    ?>
</div>
<?php yii\widgets\Pjax::end() ?>
<script>
    function toggle_favorite(event) {
        event.preventDefault();
        $.ajax({
            url: '/products/toggle-favorite',
            data: {id: event.target.dataset.id},
            success: function (data, textStatus, jqXHR) {
                $.pjax.reload({container: "#products"});

            }
        });
    }
</script>